//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id_report { get; set; }
        public int id_us { get; set; }
        public int type_report { get; set; }
        public string data { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual User User { get; set; }
    }
}
