//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Operation
    {
        public int id { get; set; }
        public int id_rol { get; set; }
        public int id_operation { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
