//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id_us { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int id_rol { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
