//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEvaluation
    {
        public int id_evaluation { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string result { get; set; }
        public string notes { get; set; }
        public string username { get; set; }
        public int state { get; set; }
    }
}
